# legal_kb.py — Complete Indian Legal Knowledge Base

IPC_SECTIONS = [
    {"keywords": ["murder", "killed", "shot dead", "stabbed to death", "poisoned to death"],
     "section": "Section 302 IPC", "title": "Murder",
     "description": "Whoever commits murder shall be punished.",
     "punishment": "Death or imprisonment for life, and fine",
     "bailable": False, "cognizable": True, "category": "Offences Against Body",
     "court": "Sessions Court", "compoundable": False},
    {"keywords": ["culpable homicide", "not murder", "without intention to kill"],
     "section": "Section 304 IPC", "title": "Culpable Homicide Not Amounting to Murder",
     "description": "Causing death with knowledge but without intention.",
     "punishment": "Imprisonment up to 10 years or life, and fine",
     "bailable": False, "cognizable": True, "category": "Offences Against Body",
     "court": "Sessions Court", "compoundable": False},
    {"keywords": ["attempt to murder", "tried to kill", "attempted murder", "shot at me", "stabbed me"],
     "section": "Section 307 IPC", "title": "Attempt to Murder",
     "description": "Whoever does any act with intention or knowledge to cause death.",
     "punishment": "Imprisonment up to 10 years and fine; if hurt caused, life imprisonment",
     "bailable": False, "cognizable": True, "category": "Offences Against Body",
     "court": "Sessions Court", "compoundable": False},
    {"keywords": ["negligent death", "accidental death", "caused death by mistake"],
     "section": "Section 304A IPC", "title": "Causing Death by Negligence",
     "description": "Causing death by a rash or negligent act.",
     "punishment": "Imprisonment up to 2 years or fine or both",
     "bailable": True, "cognizable": True, "category": "Offences Against Body",
     "court": "Magistrate Court", "compoundable": False},
    {"keywords": ["grievous hurt", "serious injury", "broken bone", "permanent damage", "acid attack", "disfigured"],
     "section": "Section 325 IPC", "title": "Voluntarily Causing Grievous Hurt",
     "description": "Voluntarily causing grievous hurt to any person.",
     "punishment": "Imprisonment up to 7 years and fine",
     "bailable": False, "cognizable": True, "category": "Offences Against Body",
     "court": "Magistrate Court", "compoundable": True},
    {"keywords": ["hurt", "beaten", "beat up", "punched", "kicked", "slapped", "hit me", "hit him", "hit her", "assault"],
     "section": "Section 323 IPC", "title": "Voluntarily Causing Hurt",
     "description": "Voluntarily causing hurt to any person.",
     "punishment": "Imprisonment up to 1 year or fine up to ₹1000 or both",
     "bailable": True, "cognizable": False, "category": "Offences Against Body",
     "court": "Magistrate Court", "compoundable": True},
    {"keywords": ["wrongful confinement", "locked up illegally", "confined illegally", "held against will"],
     "section": "Section 342 IPC", "title": "Wrongful Confinement",
     "description": "Wrongfully confining any person.",
     "punishment": "Imprisonment up to 1 year or fine up to ₹1000 or both",
     "bailable": True, "cognizable": False, "category": "Offences Against Body",
     "court": "Magistrate Court", "compoundable": True},
    {"keywords": ["rape", "sexual assault", "forced sex", "sexually assaulted", "gang rape"],
     "section": "Section 376 IPC", "title": "Rape",
     "description": "Sexual assault / rape of a woman.",
     "punishment": "Rigorous imprisonment not less than 10 years, may extend to life",
     "bailable": False, "cognizable": True, "category": "Offences Against Women",
     "court": "Sessions Court", "compoundable": False},
    {"keywords": ["molestation", "outrage modesty", "touched inappropriately", "groped", "indecent touch"],
     "section": "Section 354 IPC", "title": "Assault or Criminal Force to Outrage Modesty of Woman",
     "description": "Assault or criminal force to outrage modesty of a woman.",
     "punishment": "Imprisonment not less than 1 year, may extend to 5 years, and fine",
     "bailable": False, "cognizable": True, "category": "Offences Against Women",
     "court": "Magistrate Court", "compoundable": False},
    {"keywords": ["stalking", "following woman", "stalked", "monitor online", "obsessively following"],
     "section": "Section 354D IPC", "title": "Stalking",
     "description": "Following, contacting or monitoring a woman despite her disinterest.",
     "punishment": "First offence: up to 3 years; Subsequent: up to 5 years and fine",
     "bailable": False, "cognizable": True, "category": "Offences Against Women",
     "court": "Magistrate Court", "compoundable": False},
    {"keywords": ["domestic violence", "husband beats", "wife beaten", "cruelty by husband",
                  "cruelty by in-laws", "beats me", "abused by spouse", "husband tortures"],
     "section": "Section 498A IPC", "title": "Cruelty by Husband or Relatives",
     "description": "Husband or relative subjecting a woman to cruelty.",
     "punishment": "Imprisonment up to 3 years and fine",
     "bailable": False, "cognizable": True, "category": "Offences Against Women",
     "court": "Magistrate Court", "compoundable": False},
    {"keywords": ["dowry death", "dowry harassment", "burned for dowry", "killed for dowry", "dowry demand"],
     "section": "Section 304B IPC", "title": "Dowry Death",
     "description": "Death of woman in connection with dowry demand.",
     "punishment": "Imprisonment not less than 7 years, may extend to life",
     "bailable": False, "cognizable": True, "category": "Offences Against Women",
     "court": "Sessions Court", "compoundable": False},
    {"keywords": ["voyeurism", "secretly filmed", "recorded without consent", "bathroom camera", "spy camera"],
     "section": "Section 354C IPC", "title": "Voyeurism",
     "description": "Watching or capturing image of a woman in private act.",
     "punishment": "First offence: 1 to 3 years; Subsequent: 3 to 7 years and fine",
     "bailable": False, "cognizable": True, "category": "Offences Against Women",
     "court": "Magistrate Court", "compoundable": False},
    {"keywords": ["sexual harassment workplace", "office harassment", "boss harassing", "workplace sexual"],
     "section": "Section 354A IPC / POSH Act 2013", "title": "Sexual Harassment",
     "description": "Sexual harassment of woman at workplace or in public.",
     "punishment": "Imprisonment up to 3 years or fine or both",
     "bailable": True, "cognizable": True, "category": "Offences Against Women",
     "court": "Magistrate Court", "compoundable": False},
    {"keywords": ["theft", "stole", "stolen", "shoplifting", "pickpocket", "wallet stolen", "phone stolen"],
     "section": "Section 379 IPC", "title": "Theft",
     "description": "Whoever commits theft shall be punished.",
     "punishment": "Imprisonment up to 3 years or fine or both",
     "bailable": True, "cognizable": True, "category": "Property Offences",
     "court": "Magistrate Court", "compoundable": False},
    {"keywords": ["robbery", "robbed", "snatching", "chain snatching", "mugging", "looted"],
     "section": "Section 392 IPC", "title": "Robbery",
     "description": "Committing theft with voluntary hurt to commit or escape.",
     "punishment": "Rigorous imprisonment up to 10 years and fine",
     "bailable": False, "cognizable": True, "category": "Property Offences",
     "court": "Sessions Court", "compoundable": False},
    {"keywords": ["dacoity", "armed robbery", "gang robbery", "looted by gang"],
     "section": "Section 395 IPC", "title": "Dacoity",
     "description": "Robbery committed by five or more persons.",
     "punishment": "Imprisonment for life or rigorous imprisonment up to 10 years and fine",
     "bailable": False, "cognizable": True, "category": "Property Offences",
     "court": "Sessions Court", "compoundable": False},
    {"keywords": ["extortion", "blackmail", "extorted", "demanded money with threat", "pay or else"],
     "section": "Section 384 IPC", "title": "Extortion",
     "description": "Putting a person in fear of injury to commit extortion.",
     "punishment": "Imprisonment up to 3 years or fine or both",
     "bailable": False, "cognizable": True, "category": "Property Offences",
     "court": "Magistrate Court", "compoundable": False},
    {"keywords": ["trespass", "entered my property", "broke into", "unauthorized entry", "encroachment"],
     "section": "Section 447 IPC", "title": "Criminal Trespass",
     "description": "Entering property in possession of another with intent to commit offence.",
     "punishment": "Imprisonment up to 3 months or fine up to ₹500 or both",
     "bailable": True, "cognizable": False, "category": "Property Offences",
     "court": "Magistrate Court", "compoundable": True},
    {"keywords": ["property damaged", "vandalism", "broke my property", "destroyed property", "smashed"],
     "section": "Section 427 IPC", "title": "Mischief Causing Damage",
     "description": "Committing mischief and causing loss or damage.",
     "punishment": "Imprisonment up to 2 years or fine or both",
     "bailable": True, "cognizable": False, "category": "Property Offences",
     "court": "Magistrate Court", "compoundable": True},
    {"keywords": ["fraud", "cheated", "deceived", "scam", "conned", "duped", "money fraud", "financial fraud"],
     "section": "Section 420 IPC", "title": "Cheating and Dishonestly Inducing Delivery of Property",
     "description": "Whoever cheats and thereby dishonestly induces delivery of property.",
     "punishment": "Imprisonment up to 7 years and fine",
     "bailable": False, "cognizable": True, "category": "Fraud & Cheating",
     "court": "Magistrate Court", "compoundable": False},
    {"keywords": ["forgery", "forged signature", "forged document", "fake document", "fake certificate"],
     "section": "Section 465 IPC", "title": "Forgery",
     "description": "Making any false document or false electronic record.",
     "punishment": "Imprisonment up to 2 years or fine or both",
     "bailable": True, "cognizable": False, "category": "Fraud & Cheating",
     "court": "Magistrate Court", "compoundable": False},
    {"keywords": ["breach of trust", "misappropriation", "entrusted money", "embezzlement"],
     "section": "Section 406 IPC", "title": "Criminal Breach of Trust",
     "description": "Dishonest misappropriation of property entrusted.",
     "punishment": "Imprisonment up to 3 years or fine or both",
     "bailable": True, "cognizable": True, "category": "Fraud & Cheating",
     "court": "Magistrate Court", "compoundable": False},
    {"keywords": ["cheque bounce", "dishonoured cheque", "bounced cheque", "cheque returned"],
     "section": "Section 138 NI Act", "title": "Cheque Dishonour",
     "description": "Dishonour of cheque for insufficiency of funds.",
     "punishment": "Imprisonment up to 2 years or fine up to twice the cheque amount or both",
     "bailable": True, "cognizable": False, "category": "Fraud & Cheating",
     "court": "Magistrate Court", "compoundable": True},
    {"keywords": ["hacking", "hacked", "unauthorized access", "account hacked", "system hacked", "data breach"],
     "section": "Section 66 IT Act 2000", "title": "Computer Related Offences / Hacking",
     "description": "Dishonestly or fraudulently doing any act referred to in section 43.",
     "punishment": "Imprisonment up to 3 years or fine up to ₹5 lakh or both",
     "bailable": True, "cognizable": True, "category": "Cyber Crime",
     "court": "Magistrate Court", "compoundable": False},
    {"keywords": ["identity theft", "impersonation online", "used my identity", "fake profile online"],
     "section": "Section 66C IT Act 2000", "title": "Identity Theft",
     "description": "Fraudulently making use of electronic signature or password of another.",
     "punishment": "Imprisonment up to 3 years and fine up to ₹1 lakh",
     "bailable": True, "cognizable": True, "category": "Cyber Crime",
     "court": "Magistrate Court", "compoundable": False},
    {"keywords": ["online fraud", "cyber fraud", "upi fraud", "otp fraud", "bank fraud online"],
     "section": "Section 66D IT Act 2000", "title": "Cheating by Personation Using Computer",
     "description": "Cheating by personation using any communication device or computer resource.",
     "punishment": "Imprisonment up to 3 years and fine up to ₹1 lakh",
     "bailable": True, "cognizable": True, "category": "Cyber Crime",
     "court": "Magistrate Court", "compoundable": False},
    {"keywords": ["obscene content", "pornography shared", "morphed image", "sending obscene material"],
     "section": "Section 67 IT Act 2000", "title": "Publishing Obscene Material Electronically",
     "description": "Publishing or transmitting obscene material in electronic form.",
     "punishment": "First conviction: up to 3 years and fine up to ₹5 lakh",
     "bailable": True, "cognizable": True, "category": "Cyber Crime",
     "court": "Magistrate Court", "compoundable": False},
    {"keywords": ["online threat", "threatening messages", "whatsapp threat", "email threat", "cyber threat"],
     "section": "Section 506 IPC / Section 66A IT Act", "title": "Criminal Intimidation / Online Threats",
     "description": "Threatening another with injury to person, reputation or property.",
     "punishment": "Imprisonment up to 2 years or fine or both",
     "bailable": True, "cognizable": False, "category": "Cyber Crime",
     "court": "Magistrate Court", "compoundable": True},
    {"keywords": ["kidnapping", "kidnapped", "abducted", "abduction", "taken away by force"],
     "section": "Section 363 IPC", "title": "Kidnapping",
     "description": "Kidnapping from India or from lawful guardianship.",
     "punishment": "Imprisonment up to 7 years and fine",
     "bailable": False, "cognizable": True, "category": "Kidnapping & Trafficking",
     "court": "Sessions Court", "compoundable": False},
    {"keywords": ["trafficking", "human trafficking", "forced labour", "bonded labour"],
     "section": "Section 370 IPC", "title": "Trafficking of Persons",
     "description": "Trafficking of person for exploitation.",
     "punishment": "Imprisonment not less than 7 years, may extend to life",
     "bailable": False, "cognizable": True, "category": "Kidnapping & Trafficking",
     "court": "Sessions Court", "compoundable": False},
    {"keywords": ["defamation", "false statement about me", "reputation damaged", "slander", "libel"],
     "section": "Section 500 IPC", "title": "Defamation",
     "description": "Whoever defames another person shall be punished.",
     "punishment": "Simple imprisonment up to 2 years or fine or both",
     "bailable": True, "cognizable": False, "category": "Defamation",
     "court": "Magistrate Court", "compoundable": True},
    {"keywords": ["riot", "rioting", "mob violence", "unlawful assembly", "mob attack"],
     "section": "Section 147 IPC", "title": "Rioting",
     "description": "Being a member of an unlawful assembly using force or violence.",
     "punishment": "Imprisonment up to 2 years or fine or both",
     "bailable": False, "cognizable": True, "category": "Public Order",
     "court": "Magistrate Court", "compoundable": False},
    {"keywords": ["rash driving", "road accident", "hit and run", "ran over", "car accident", "bike accident"],
     "section": "Section 279/304A IPC + Section 134 MVA", "title": "Rash Driving / Road Accident",
     "description": "Rash or negligent driving causing hurt or death.",
     "punishment": "Imprisonment up to 6 months (rash); up to 2 years (death by negligence)",
     "bailable": True, "cognizable": True, "category": "Motor Vehicle",
     "court": "Magistrate Court", "compoundable": False},
    {"keywords": ["bribery", "bribe", "corruption", "demanded bribe", "paid bribe"],
     "section": "Section 7/13 Prevention of Corruption Act 1988", "title": "Bribery / Corruption",
     "description": "Public servant obtaining valuable thing without consideration.",
     "punishment": "Imprisonment from 3 to 7 years and fine",
     "bailable": False, "cognizable": True, "category": "Corruption",
     "court": "Special Court", "compoundable": False},
    {"keywords": ["consumer complaint", "defective product", "poor service", "overcharged", "not refunded"],
     "section": "Consumer Protection Act 2019", "title": "Consumer Grievance / Deficiency in Service",
     "description": "Deficiency in service or unfair trade practice.",
     "punishment": "Fine and compensation as directed by Consumer Court",
     "bailable": True, "cognizable": False, "category": "Consumer Protection",
     "court": "Consumer Forum", "compoundable": True},
    {"keywords": ["medical negligence", "doctor negligence", "wrong treatment", "hospital negligence"],
     "section": "Section 304A IPC + Consumer Protection Act", "title": "Medical Negligence",
     "description": "Negligent medical treatment causing hurt or death.",
     "punishment": "Imprisonment up to 2 years or fine or both",
     "bailable": True, "cognizable": True, "category": "Medical Negligence",
     "court": "Magistrate Court / Consumer Forum", "compoundable": False},
    {"keywords": ["drugs", "narcotics", "drug trafficking", "selling drugs", "drug possession"],
     "section": "NDPS Act 1985 (Section 20/21/22)", "title": "Narcotic Drugs / Substance Offences",
     "description": "Production, possession, sale or transport of narcotics.",
     "punishment": "Imprisonment from 6 months to 20 years depending on quantity",
     "bailable": False, "cognizable": True, "category": "Narcotics",
     "court": "Special Court", "compoundable": False},
]

VICTIM_PHRASES = [
    "someone hit me", "i was attacked", "they stole", "he hit me", "she hit me",
    "they attacked", "i was cheated", "i was harassed", "i was threatened",
    "my property", "i lost my", "someone broke", "i was robbed", "i was raped",
    "they kidnapped", "i was stalked", "i was blackmailed", "i was scammed",
    "they hacked", "my account was", "i was defrauded", "i was beaten",
    "someone molested", "they threatened me", "my phone was stolen",
    "he assaulted", "she assaulted", "they extorted", "beat me up", "beats me",
    "stole my", "hacked my", "cheated me", "threatened me", "harassed me",
    "stalked me", "robbed me", "scammed me", "someone hacked", "my husband beats",
    "neighbour beat", "they took my", "i was deceived", "we were attacked",
    "my money was", "damaged my", "destroyed my", "forged my", "used my identity",
    "blackmailing me", "extorting me", "snatched my", "following me",
    "recording me", "filmed me secretly", "without my consent", "without my knowledge",
    "false rumour", "spreading lies about me", "i have been cheated",
    "i have been attacked", "i have been harassed", "i have been threatened",
]

FAULT_PHRASES = [
    "i hit", "i stole", "i attacked", "i threatened", "i forged", "i hacked",
    "i cheated", "i beat", "i killed", "i stabbed", "i robbed", "i molested",
    "i raped", "i assaulted", "i trespassed", "i stalked", "i bribed",
    "i defrauded", "i vandalized", "i was driving rashly", "i committed",
    "i am guilty", "i did it", "i took without permission",
]
